Add ecommerce layouts
Voog/design-paris pull request #152
Opened 2021-08-27 06:46 UTC by robertpih

Closes #149

2021-09-02 11:17 UTC, tanelj requested changes
Toimi kenasti ja ootuspäraselt, kuid kiirel testil jäid silma mõned nüansid:

* [ ] Toodete lehe korral kuvatakse II taseme menüüs toote ja toote listi lehti. Ei tohiks.
* [ ] Kui tootel pilti ei ole, siis preview vaates peaks pildi alune tekst ja vasak poolne tekstiala olema ühel joonel.
![Screenshot 2021-09-02 at 14 10 35](https://user-images.githubusercontent.com/378755/131833673-13266926-eb01-4edb-ba75-d55c6368d24b.png)
* [ ] II taseme menüü ja toote lehe sisu vahel võiks veidi suurem ruum olla.
![Screenshot 2021-09-02 at 14 12 45](https://user-images.githubusercontent.com/378755/131834043-482af93e-5430-469a-b9d5-d89834f16be7.png)

2021-09-08 14:31 UTC, tanelj requested changes
Muidu kena, kuid kaks bugi jäid silma.

2021-09-08 14:31 UTC, tanelj commented on layouts/product_list.tpl
> +          {% include 'menu-breadcrumbs' %}
Ka listingu lehel peaks tavalist tüüpi II taseme lehed näha olema. Seega siin ees peaks olema:

```
{% include "menu-level-2" %}
```

2021-09-08 14:31 UTC, tanelj commented on components/menu-level-1-link.tpl
> +  <a class="menu-link{% if item.selected? %} active{% endif %}{% unless item.translated? %}fci-editor-menuadd untranslated{% endunless %}" href="{{ item.url }}">{{ item.title }}</a>
Siin on klassid ja stiilid katki läinud. Tühik on puudu ja seega tekib tõlkimata puhul:

```
class="menu-linkfci-editor-menuadd untranslated"
```

Eelistatud kasutus oleks muidugi [menulink](https://www.voog.com/developers/markup/tags/menulink) tag. Kuid sellega ei saa anda kaasa lisa klassi  (<a class="menu-link"), ning see eeldaks, et stiilid peaks olema `.menu-sub .menu-link` a la asemel `.menu-sub .menu-item a`

```
{% menulink item selected-class="active" %}
```

2021-09-08 18:23 UTC, robertpih commented on components/menu-level-1-link.tpl
> +  <a class="menu-link{% if item.selected? %} active{% endif %}{% unless item.translated? %}fci-editor-menuadd untranslated{% endunless %}" href="{{ item.url }}">{{ item.title }}</a>
Lähen hetkel lihtsama vastupanu teed. :)

2021-09-08 19:17 UTC, tanelj approved these changes

2021-09-08 19:34 UTC, tanelj requested changes

2021-09-08 19:34 UTC, tanelj commented on components/html-head.tpl
> +{%- endcapture -%}
Ka JS data snipet tuleb välja renderdada
```liquid
{{ breadcrumbsScript }}
```

2021-09-10 18:15 UTC, robertpih commented on components/menu-level-2.tpl
> +                <li class="menu-item"><a class="menu-link{% if subitem.selected? %} active{% endif %}{% unless subitem.translated? %} untranslated fci-editor-menuadd{% endunless %}" href="{{ subitem.
Jah, võimalik oleks, kuid hetkel jätaks nii nagu on.

2021-09-14 07:44 UTC, robertpih commented on components/menu-breadcrumbs.tpl
> +            {{ listItem.item.name }}
See tuleneb tegelikult if-lausetest (rida 7 ja 23 - https://shopify.github.io/liquid/basics/whitespace/). 
Praegune whitespace sobituks justkui kujundusega hästi kokku ja jätab silmale viisaka vahe sisse, kuid ma ei tea, mis siin hea tava on. Kas jätta whitespace, või teha ümber CSSi abil..

2021-09-16 13:15 UTC, tanelj approved these changes

2021-09-17 09:37 UTC, pxska approved these changes
![image](https://user-images.githubusercontent.com/48313701/133761609-a4461ce1-ecfc-4c17-a29b-47621163278e.png)

2021-09-17 10:33 UTC, merged