Add auto-rendered product layout
Voog/design-paris pull request #154
Opened 2022-02-08 12:23 UTC by PeeterPaal

Adds auto-rendered product layout.
Also adds a browser hack to enhance image rendering in Chrome based browsers.
Closes #153

2022-02-09 17:18 UTC, pxska approved these changes
Good job! 👍🏻

2022-02-10 08:48 UTC, tanelj requested changes
Nice, but default colors should be different.

2022-02-10 12:39 UTC, tanelj requested changes
Works as expected, but there is one JS error:

* [x] `BgPicker's `el` parameter has to be either a plain DOM node or a jQuery object around a DOM node.` Since there has no BG picker area on page. `Edicy.BgPicker()` requires the target element present on the page: https://github.com/Edicy/design-paris/blob/fda5bc0679b111687c911ef1102f1bf83ef85b73/components/edicy-tools.tpl#L20

2022-02-10 13:24 UTC, tanelj approved these changes

2022-02-10 13:27 UTC, pxska approved these changes

2022-02-10 20:49 UTC, merged