Improve auto-rendered product pages
Voog/design-paris pull request #158
Opened 2022-03-08 07:41 UTC by PeeterPaal

Closes #157

2022-03-08 08:12 UTC, tanelj requested changes
Nice, but one minor comment.

2022-03-08 08:12 UTC, tanelj commented on components/template-meta.tpl
> +  {% if og_obj.image == nil %}
The fallback should not use in case of autp-gen product page.

```suggestion
  {% if og_obj.image == nil and product == nil %}
```

2022-03-09 15:14 UTC, tanelj approved these changes
Nice!

2022-03-10 08:21 UTC, pxska approved these changes
Looks good!

2022-03-10 09:06 UTC, merged